HSE/HSE/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("education/", include("education.urls")),
    path("accounts/", include("allauth.urls")),
    path("mypage/", include("mypage.urls")),
    path("apply/", include("apply.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HSE/education/urls.py
from django.urls import path
from .views import *

app_name = "education"

urlpatterns = [
    path("<int:id>/", detail, name="detail"),  # 글 상세 페이지
    path("new/", new, name="new"),  # 새 글 작성 페이지
    path("create/", create, name="create"),  # 새 글 작성 동작
    path("edit/<int:id>", edit, name="edit"),  # 기존 글 수정 페이지
    path("update/<int:id>", update, name="update"),  # 기존 글 수정 동작
    path("delete/<int:id>", delete, name="delete"),  # 기존 글 삭제
    path("", edulist, name="edulist"),  # 글 목록 페이지
]

HSE/main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", showMain,name="showMain"),
]

HSE/mypage/urls.py
from django.urls import path
from .import views

app_name="mypage"

urlpatterns=[
    path('mypage/', views.mypage, name="mypage")    # 사용자 프로필 보여주는 mypage
]

HSE/HSE/templates/shared/footer.html
<footer class="footer-container white-text-container" style="background-color : rgba(165, 211, 206, 0.904)">
    <div class="container">
        <div class="row">
                <div class="col-md-4">
                    <h4>About us</h4>
                    <p>HSE의 의미는 HI-SW-Education의 약자로 하이소프트웨어 봉사단의 교육체계를 발전시키기 위해 제작된 서비스입니다.</p>
                </div>

                <div class="col-md-4">
                    <h4>Developed by</h4>
                    <div>
                        <p><small>HSE(박상준,서희찬,이태검,정민경)</small></p>
                    </div>

                </div>

                <div class="col-md-4">
                        
                    <h4>Version</h4>
                    <p>2.1</p>
                        
                        
                    </div>
                </div>
        </div>
    </div>
</footer>

HSE/HSE/templates/shared/navbar.html
<style>
  @media screen and (max-width: 768px) {
    .navbar {
            flex-direction: column;
            align-items: flex-start;
            padding: 8px 24px;
    }
    .nav{

    }
    .navbar__menu {
            display: none;
            flex-direction: column;
            align-items: center;
            width: 100%;
    }
    .navbar__menu li {
            width: 100%;
            text-align: center;
    }
    .navbar__toggleBtn {
             display: block;
     }
    .navbar__menu.active,
    .navbar__sns.active {
            display: flex;
    }
}
.on{
    color:orange;
}
.on:hover{
    color: #868686;
}
</style>

<header style="margin-bottom: 100px;">
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:rgba(165, 211, 206, 0.904)">
      <div class="container">
        <div class="navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'main:showMain' %}"><img src="../../static/images/main.png" width="30px"alt="main"></a></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                  <p>
                    <!-- 교육페이지 -->
                      <a href="{% url 'education:edulist'%}" class="btn btn-default navbar-btn" >Education</a>
                      <!-- 지원페이지 -->
                      
                       {%if user.is_authenticated%}
                      <a href="{%url 'mypage:mypage' %}" class="btn btn-default navbar-btn" >Profile</a> 
                      <a href="{%url 'account_logout'%}" class="btn btn-default navbar-btn" >Log-out</a> 
                      {%else%}
                        <a href="{%url 'account_login'%}" class="btn btn-default navbar-btn" >Log-in</a> 
                      {%endif%}

                  </p>
              </li>
          </ul>
        </div>
        
        <div class="navbar-toggle">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'main:showMain' %}"><img src="../../static/images/main.png" width="30px"alt="main"></a></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                  <p>
                    <!-- 교육페이지 -->
                      <a href="{% url 'education:edulist'%}" class="btn btn-default navbar-btn" >Education</a>
                      <!-- 지원페이지 -->
                      
                       {%if user.is_authenticated%}
                      <a href="{%url 'mypage:mypage' %}" class="btn btn-default navbar-btn" >Profile</a> 
                      <a href="{%url 'account_logout'%}" class="btn btn-default navbar-btn" >Log-out</a> 
                      {%else%}
                        <a href="{%url 'account_login'%}" class="btn btn-default navbar-btn" >Log-in</a> 
                      {%endif%}

                  </p>
              </li>
          </ul>
        </div>


      </div>
    </nav>



  </header>
  