HSE/HSE/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("education/", include("education.urls")),
    path("accounts/", include("allauth.urls")),
    path("mypage/", include("mypage.urls")),
    path("apply/", include("apply.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HSE/apply/urls.py
from django.urls import path
from . import views

app_name = "apply"
urlpatterns = [
   

    path('apply_main_sub/<int:post_id>',views.apply_main_sub, name="apply_main_sub"), # post_id에 대응하는 봉사에 신청하기위해 apply_main_sub로 이동
    path('apply_new/',views.apply_new, name="apply_new"), # db에 저장하기위해 views에 db에 저장하는 apply_new로 이동
    path('apply_result/<int:post_id>',views.apply_result, name="apply_result"), # 결과를 보기위해 views에 apply_result로 이동
  

]

HSE/education/urls.py
from django.urls import path
from .views import *

app_name = "education"

urlpatterns = [
    path("<int:id>/", detail, name="detail"),  # 글 상세 페이지
    path("new/", new, name="new"),  # 새 글 작성 페이지
    path("create/", create, name="create"),  # 새 글 작성 동작
    path("edit/<int:id>", edit, name="edit"),  # 기존 글 수정 페이지
    path("update/<int:id>", update, name="update"),  # 기존 글 수정 동작
    path("delete/<int:id>", delete, name="delete"),  # 기존 글 삭제
    path("", edulist, name="edulist"),  # 글 목록 페이지
]

HSE/education/models.py
from django.db import models
from django.db.models.aggregates import Max
from django.contrib.auth.models import User

# Create your models here.
class EduPost(models.Model):
    title = models.CharField(max_length=200)  # 봉사활동 이름
    writer = models.ForeignKey(User, on_delete=models.CASCADE)  # 작성자, User 모델 사용
    pub_date = models.DateTimeField()  # 글 최초 작성 일자
    due_date = models.DateTimeField()  # 봉사활동 마감 일자
    work_date = models.DateTimeField(null=True)  # 봉사활동 예정 일자(실제 봉사 하는 날)
    main_teacher = models.IntegerField()  # 모집하는 주 강사 수
    sub_teacher = models.IntegerField()  # 모집하는 보조 강사 수
    work_hour = models.IntegerField()  # 봉사활동 인정 시간(0도 가능)
    body = models.TextField()  # 봉사활동 관련 설명 본문
    video = models.CharField(null=True, max_length=200)  # 유튜브에 업로드한 동영상 url
    image = models.FileField(
        upload_to="image/", null=True
    )  # 봉사활동 관련 이미지(있으면 글 썸네일, 없으면 메인 로고가 글 썸네일)
    extrafile = models.FileField(
        upload_to="extrafiles/", null=True
    )  # 추가적으로 필요한 파일(봉사활동 관련 pdf 등)
    count = models.IntegerField(default=0)  # 각 봉사당 결과가 한번만 랜덤으로 선정되게 count 값을 통해 확인
    """ count 만들기 전 봉사자로 선정된 결과를 확인할 때마다 랜덤으로 봉사자 중 뽑게돼서 
    이를 막기 위해 count = 0일 때만 봉사자를 뽑고 그 이후로 결과 확인을 해도 뽑힌 봉사자가 변하지 않도록 설정"""

HSE/education/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import EduPost
from apply.models import apply
from django.utils import timezone
import datetime

# Create your views here.

# 봉사활동 게시글 목록 보여주는 페이지
def edulist(request):
    post = EduPost.objects.all()
    post = post.order_by("-pub_date")
    return render(request, "education/edulist.html", {"posts": post})


# 봉사활동 게시글 상세 페이지
def detail(request, id):
    post = get_object_or_404(EduPost, pk=id)
    # author: 현재 유저가 게시글 작성자와 동일한지 전달하는 변수 (이후 수정하기, 삭제하기 버튼 띄울지 말지 결정)
    if request.user == post.writer:
        author = True
    else:
        author = False
    # cmp에 현재 시간 받아와서 저장하고 형식 맞춘 후 pub_date와 비교하여 마감됐는지 확인하고 저장
    cmp = datetime.datetime.now()
    cmp = cmp.strftime("%y-%m-%d %H:%M:%S")
    cmp = datetime.datetime.strptime(cmp, "%y-%m-%d %H:%M:%S")
    if post.due_date >= cmp:
        is_dead = True
    else:
        is_dead = False
    # 봉사 게시글 정보, 글 작성자 여부, 봉사 마감 여부 전달
    return render(
        request,
        "education/detail.html",
        {"post": post, "author": author, "is_dead": is_dead},
    )


# 새 글 작성 페이지
def new(request):
    return render(request, "education/new.html")


# 새 글 작성 동작
def create(request):
    # 모델 설명과 동일
    new_post = EduPost()
    new_post.title = request.POST["title"]
    new_post.writer = request.user  # 현재 접속한 유저를 글 작성자로
    new_post.pub_date = timezone.now()  # 현재 시간을 게시글 작성 시간으로
    new_post.due_date = request.POST["due_date"]
    new_post.work_date = request.POST["work_date"]
    new_post.main_teacher = request.POST["main_teacher"]
    new_post.sub_teacher = request.POST["sub_teacher"]
    new_post.work_hour = request.POST["work_hour"]
    new_post.body = request.POST["body"]
    # 입력한 유튜브 동영상 주소에서 필요없는 부분 제하고 iframe 형식 맞추기 (& 뒤에 재생시간 정보가 있어서 제거)
    new_post.video = request.POST["video"].replace("watch?v=", "embed/")
    if "&" in new_post.video:
        new_post.video = new_post.video[: new_post.video.index("&")]
    new_post.extrafile = request.FILES.get("extrafile")
    new_post.image = request.FILES.get("image")
    new_post.save()

    return redirect("education:detail", new_post.id)


# 기존 봉사 게시글 수정 페이지
def edit(request, id):
    edit_post = EduPost.objects.get(id=id)
    # author : 현재 접속한 유저가 수정하려는 게시글의 작성자인지 확인하고 저장
    if request.user == edit_post.writer:
        author = True
    else:
        author = False
    return render(request, "education/edit.html", {"post": edit_post, "author": author})


# 기존 봉사 게시글 수정 동작
def update(request, id):
    ap_all = apply.objects.all()
    update_post = EduPost.objects.get(id=id)
    update_post.title = request.POST["title"]
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.due_date = request.POST["due_date"]
    update_post.main_teacher = request.POST["main_teacher"]
    update_post.sub_teacher = request.POST["sub_teacher"]
    update_post.work_hour = request.POST["work_hour"]
    update_post.body = request.POST["body"]
    update_post.video = request.POST["video"].replace("watch?v=", "embed/")
    if "&" in update_post.video:
        update_post.video = update_post.video[: update_post.video.index("&")]
    update_post.extrafile = request.FILES.get("extrafile")
    update_post.image = request.FILES.get("image")
    update_post.count = 0
    for i in ap_all:
        if i.title == update_post.title:
            i.winner = ""
            i.save()
    update_post.save()

    return redirect("education:detail", update_post.id)


# 봉사 게시글 삭제
def delete(request, id):
    delete_post = EduPost.objects.get(id=id)
    delete_post.delete()

    return redirect("education:edulist")

HSE/education/templates/education/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section style="margin:0px 200px; margin-top:80px;">
    <h2 style="font-family: 'Nanum Gothic Coding', sans-serif;">{{post.title}}</h2>
    <p>작성자 : {{post.writer}} / 작성 날짜 : {{post.pub_date}}</p>
    <hr>
    {% if post.video%}
    <!-- 유튜브 주소를 줬다면 영상 가져와서 띄우기 -->
        <iframe width="560" height="315" src="{{post.video}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    {% endif %}
    <p>신청 기한: {{post.due_date}}</p>
    <p>주 강사: {{post.main_teacher}}명 / 보조 강사: {{post.sub_teacher}}명</p>
    <p>봉사 일시: {{post.work_date}}</p>
    <p>인정 봉사 시간: {{post.work_hour}}시간</p>
    {% if post.image%}
    <!-- 이미지가 있다면 띄우기 -->
        <p><img src="{{ post.image.url }}" style="width:60%" alt="사진"></p>
    {% endif %}
    <p><pre>{{post.body}}</pre></p>
    {% if post.extrafile%}
    <!-- 추가 파일이 있다면 띄우기 -->
        <p>
            Attachment: <a class="btn" href="{{ post.extrafile.url }}" target="_blank">{{post.extrafile.name}}</a>
        </p>
    {% endif %}

    {%if author%}
    <!-- 현재 접속자가 현재 봉사 글 작성자라면 버튼 띄우기 -->
        <a href="{%url 'education:edit' post.id %}" class="btn_post">수정하기</a>
        <a href="{%url 'education:delete' post.id %}" class="btn_post">삭제하기</a>
    {%endif%}

    {%if is_dead%}
    <!-- 마감하되기 전이라면 신청하기 버튼 -->
        <a href="{%url 'apply:apply_main_sub' post.id %}" class="btn_post">신청하기</a>
    {%else%}
    <!-- 마감된 후라면 결과 보기 버튼 -->
        <a href="{%url 'apply:apply_result' post.id %}" class="btn_post">결과 보기</a>
    {%endif%}
</section>
{% endblock %}

HSE/education/templates/education/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
<section style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">
{%if user.is_superuser and author%}
<!-- author를 통해 수정 권한 확인 -->
	<form action="{% url 'education:update' post.id %}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title" value="{{post.title}}" required></p>
		<p>마감 날짜: <input type="datetime-local" name="due_date" value="{{post.due_date}}" required></p>
		<p>주 강사 수: <input type="number" name="main_teacher" value="{{post.main_teacher}}" required></p>
		<p>보조 강사 수: <input type="number" name="sub_teacher" value="{{post.sub_teacher}}" required></p>
		<p>봉사 일시: <input type="datetiem-local" name="work_date" value="{{post.work_date}}" required></p>
		<p>인정 봉사 시간 : <input type="number" name="work_hour" value="{{post.work_hour}}" required></p>
		<p>설명 영상 : <input type="text" name="video" value="{{post.video}}"> (해당 동영상 유튜브 페이지 url 적어주세요)</p>
		<p>사진: <input type="file" name="image"></p>
		<p>내용 : <textarea style="width:100%;" type="text" name="body" id="" cols="130" rows="50">{{post.body}}</textarea></p>
		<p>추가 첨부파일: <input type="file" name="extrafile"></p>
		<button type="submit">제출</button>
	</form>
{%else%}
<!-- 글 쓴 사람 아니면 권한이 없으므로 돌려보내기-->
	<script>
		alert("권한이 없습니다.");
		window.location.href="{%url 'education:edulist'%}"
	</script>
{%endif%}
</section>
{% endblock %} 

HSE/education/templates/education/edulist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">
{%if user.is_authenticated%}
<!-- 로그인한 사람만 봉사 목록 확인 가능 -->
    <h2 style="font-family: 'Nanum Gothic Coding', sans-serif;">봉사 목록</h2>
    {%if user.is_superuser%} 
    <!-- superuser만 글 작성 가능(일반 유저는 글 작성 불가) -->
        <a href="{%url 'education:new' %}">새 봉사 올리기</a>
    {%endif%}
    {%for post in posts%}
    <hr>
    <div style="display:flex; margin: 10px 0px; height: 20vh;">
        <div style="overflow:hidden;margin:0px 30px;width:20vh; height:20vh;border:solid black 3px;border-radius:10%">
        {%if post.image%}
        <!-- 게시글에 따로 이미지가 있었으면 썸네일 제작 -->
            <img src="{{ post.image.url }}" style="object-fit: cover; width:100%; height: 100%;" alt="사진">
        {%else%}
        <!-- 게시글에 따로 이미지가 없을 경우 로고를 썸네일로 -->
            <img src="../../static/images/main.png" style="width:15vh; height:15vh; position:relative; top:2.5vh; left:2.5vh;">
        {%endif%}
        </div>
        <div style="display:flex; flex-direction: column; justify-content: space-around;">
            <a href="{%url 'education:detail' post.id%}"><h3 style="font-family: 'Nanum Gothic Coding', sans-serif;">{{post.title}}</h3></a>
            글쓴이: {{post.writer}} 
            {%if post.work_hour%}
            <!-- 봉사 인정 시간이 있다면 '봉사시간 인정' 뱃지 달아주기-->
                <div style="width: 110px;border: tomato 1px solid; padding: 3px; background-color: tomato; color:white;">봉사시간 인정</div>
            {%else%}
                <div style="width: 100px;"></div>
            {%endif%}
        </div>
    </div>
    {%endfor%}

{%else%} 
<!-- 로그인 안돼있을 경우 로그인 화면으로 윪겨주기 -->
    <script>
        alert("로그인 후 이용해주세요");
        window.location.href="{%url 'account_login'%}"
    </script>
{%endif%}
</section>
{% endblock %}

HSE/education/templates/education/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">
{%if user.is_superuser%}
<!-- 관리자만 봉사 게시글 작성 가능 -->
	<form action="{%url 'education:create'%}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title" required></p>
		<p>마감 날짜: <input type="datetime-local" name="due_date" id='currentDate' required></p>
		<p>주 강사 수: <input type="number" name="main_teacher" min="0" required></p>
		<p>보조 강사 수: <input type="number" name="sub_teacher" min="0" required></p>
		<p>봉사 일시: <input type="datetime-local" name="work_date" required></p>
		<p>인정 봉사 시간 : <input type="number" name="work_hour" min="0" required></p>
		<p>사진: <input type="file" name="image"></p>
		<p>설명 영상 : <input type="text" name="video"> (해당 동영상 유튜브 페이지 url 적어주세요)</p>
		<p>내용 :
			<textarea style="width: 100%;" type="text" name="body" id="" cols="130" rows="50">
1. 행사명:

2. 대상:

3. 일시: 

4. 장소:

5. 내용 및 세부사항: 

6. 비고:</textarea>
		</p>
		<p>추가 첨부파일: <input type="file" name="extrafile"></p>
		<button type="submit">제출</button>
	</form>
	<script>
		document.getElementById('currentDate').min = new Date().toISOString().substring(0, 10);;
	</script>
{%else%}
<!-- 괸라자가 아닌데 url로 접근하였을 경우 경고창 띄워주고 글 목록으로 이동시키기 -->
	<script>
		alert("권한이 없습니다.");
		window.location.href = "{%url 'education:edulist'%}"
	</script>
	{%endif%}
</section>
{% endblock %}